<?php

declare(strict_types=1);

namespace some\any;

return new \Phplrt\Lexer\LexerCreateInfo(
    pattern: '/\\G(?|(?:(?:"([^"\\\\]*(?:\\\\.[^"\\\\]*)*)")(*MARK:a))|(?:(?:\'([^\'\\\\]*(?:\\\\.[^\'\\\\]*)*)\')(*MARK:b))|(?:(?:\\-?(?i)[0-9]++\\.[0-9]*+(?:e-?[0-9]++)?)(*MARK:c))|(?:(?:\\-?(?i)[0-9]*+\\.[0-9]++(?:e-?[0-9]++)?)(*MARK:d))|(?:(?:\\-?(?i)[0-9]++e-?[0-9]++)(*MARK:e))|(?:(?:\\-?(?i)0b[0-1_]++)(*MARK:f))|(?:(?:\\-?(?i)0o[0-7_]++)(*MARK:g))|(?:(?:\\-?(?i)0x[0-9a-f_]++)(*MARK:h))|(?:(?:\\-?(?i)[0-9][0-9_]*+)(*MARK:i))|(?:(?:(?i)(?:true|false)\\b)(*MARK:j))|(?:(?:(?i)(?:null)(?![a-zA-Z0-9\\-_\\x80-\\xff]))(*MARK:k))|(?:(?:(?i)is\\h+not(?![a-zA-Z0-9\\-_\\x80-\\xff]))(*MARK:l))|(?:(?:(?i)is(?![a-zA-Z0-9\\-_\\x80-\\xff]))(*MARK:m))|(?:(?:\\$this\\b)(*MARK:n))|(?:(?:\\$[a-zA-Z_\\x80-\\xff][a-zA-Z0-9\\-_\\x80-\\xff]*)(*MARK:o))|(?:(?:[a-zA-Z_\\x80-\\xff][a-zA-Z0-9\\-_\\x80-\\xff]*\\s+?)(*MARK:p))|(?:(?:[a-zA-Z_\\x80-\\xff][a-zA-Z0-9\\-_\\x80-\\xff]*)(*MARK:q))|(?:(?:\\<\\=)(*MARK:r))|(?:(?:\\>\\=)(*MARK:s))|(?:(?:\\<)(*MARK:t))|(?:(?:\\>)(*MARK:u))|(?:(?:\\()(*MARK:v))|(?:(?:\\))(*MARK:w))|(?:(?:\\{)(*MARK:x))|(?:(?:\\})(*MARK:y))|(?:(?:\\#\\[)(*MARK:z))|(?:(?:\\[)(*MARK:A))|(?:(?:\\])(*MARK:B))|(?:(?:,)(*MARK:C))|(?:(?:\\.\\.\\.)(*MARK:D))|(?:(?:;)(*MARK:E))|(?:(?:\\:\\:)(*MARK:F))|(?:(?:\\:)(*MARK:G))|(?:(?:\\=)(*MARK:H))|(?:(?:\\\\)(*MARK:I))|(?:(?:\\?)(*MARK:J))|(?:(?:\\!)(*MARK:K))|(?:(?:\\|)(*MARK:L))|(?:(?:&)(*MARK:M))|(?:(?:\\\\\\*)(*MARK:N))|(?:(?:(\\/\\/|\\#).+?$)(*MARK:O))|(?:(?:\\/\\*.*?\\*\\/)(*MARK:P))|(?:(?:\\s++)(*MARK:Q))|(?:(?:(\\/\\/|\\#).+?$)(*MARK:R))|(?:(?:.+?)(*MARK:S)))/Ssum',
    channels: [
        'Q' => 'hidden',
        'S' => 'unknown',
    ],
    aliases: [
        'a' => 'T_DQ_STRING_LITERAL',
        'b' => 'T_SQ_STRING_LITERAL',
        'c' => 'T_PFX_FLOAT_LITERAL',
        'd' => 'T_SFX_FLOAT_LITERAL',
        'e' => 'T_EXP_LITERAL',
        'f' => 'T_BIN_INT_LITERAL',
        'g' => 'T_OCT_INT_LITERAL',
        'h' => 'T_HEX_INT_LITERAL',
        'i' => 'T_DEC_INT_LITERAL',
        'j' => 'T_BOOL_LITERAL',
        'k' => 'T_NULL_LITERAL',
        'l' => 0,
        'm' => 1,
        'n' => 2,
        'o' => 'T_VARIABLE',
        'p' => 'T_NAME_WITH_SPACE',
        'q' => 'T_NAME',
        'r' => 3,
        's' => 4,
        't' => 5,
        'u' => 6,
        'v' => 7,
        'w' => 8,
        'x' => 9,
        'y' => 10,
        'z' => 11,
        'A' => 12,
        'B' => 13,
        'C' => 14,
        'D' => 15,
        'E' => 16,
        'F' => 17,
        'G' => 18,
        'H' => 19,
        'I' => 20,
        'J' => 21,
        'K' => 22,
        'L' => 23,
        'M' => 24,
        'N' => 25,
        'O' => 'T_COMMENT',
        'P' => 'T_DOC_COMMENT',
        'Q' => 26,
        'R' => 'T_COMMENT',
        'S' => 27,
    ],
);