<?php

/**
 * @internal this code has been auto-generated by the phplrt compiler v4.x-dev
 */

declare(strict_types=1);

namespace Phplrt\Compiler\Syntax\PP3;

\interface_exists(\Phplrt\Contracts\Source\Exception\SourceExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Source\ReadableInterface::class);
\interface_exists(\Phplrt\Contracts\Source\FileInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\ChannelInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\TokenInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\LexerInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\LexerExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\RuntimeExceptionInterface::class);
\enum_exists(\Phplrt\Contracts\Lexer\Channel::class);
\class_exists(\Phplrt\Contracts\Lexer\UserDefinedChannel::class);
\interface_exists(\Phplrt\Contracts\Parser\ParserInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\ParserExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\RuntimeExceptionInterface::class);

/**
 * @template TResult of mixed = mixed
 *
 * @template-implements \Phplrt\Contracts\Parser\ParserInterface<TResult>
 *
 * @readonly
 */
final class PP3Parser implements \Phplrt\Contracts\Parser\ParserInterface
{
    /** @var int */
    public const T_WHITESPACE = 0;
    /** @var int */
    public const T_COMMENT = 1;
    /** @var int */
    public const T_DOC = 2;
    /** @var int */
    public const T_PRAGMA = 3;
    /** @var int */
    public const T_INCLUDE = 4;
    /** @var int */
    public const T_PHP = 5;
    /**
     * What is said about a rule or about a statement apart from what it
     * recognizes, like:
     *  - `@error("a closing parenthesis is expected")`
     *
     * The name is captured by the very token the annotation opens with, so it
     * belongs to the "@" and is never written apart from it.
     *
     * @var int
     */
    public const T_ANNOTATION = 6;
    /** @var int */
    public const T_SEMICOLON = 7;
    /** @var int */
    public const T_OR = 8;
    /** @var int */
    public const T_PARENTHESIS_OPEN = 9;
    /** @var int */
    public const T_PARENTHESIS_CLOSE = 10;
    /** @var int */
    public const T_ANGLE_OPEN = 11;
    /** @var int */
    public const T_ANGLE_CLOSE = 12;
    /** @var int */
    public const T_QUESTION_MARK = 13;
    /** @var int */
    public const T_PLUS = 14;
    /** @var int */
    public const T_ASTERISK = 15;
    /** @var int */
    public const T_BRACE_OPEN = 16;
    /** @var int */
    public const T_BRACE_CLOSE = 17;
    /** @var int */
    public const T_COMMA = 18;
    /** @var int */
    public const T_INT = 19;
    /** @var int */
    public const T_STRING = 20;
    /** @var int */
    public const T_NAME = 21;
    /**
     * A token is declared on a line of its own and is read by a lexer of its own:
     * the parts of a declaration are spelled in ways that only make sense next to
     * each other, and none of them means anything anywhere else.
     *
     * @var int
     */
    public const T_TOKEN = 22;
    /** @var int */
    public const T_SKIP = 23;
    /** @var int */
    public const T_FRAGMENT = 24;
    /** @var int */
    public const T_LEXER = 25;
    /** @var int */
    public const T_DOUBLE_COLON = 26;
    /** @var int */
    public const T_COLON = 27;
    /** @var int */
    public const T_AMPERSAND = 28;
    /** @var int */
    public const T_EXCLAMATION = 29;
    /**
     * A token a rule declares by the expression recognizing it. The comments are
     * declared before it, so a slash still opens a comment where it always did.
     *
     * @var int
     */
    public const T_REGEX = 30;

    /**
     * @var \Phplrt\Contracts\Parser\ParserInterface<TResult>
     */
    protected readonly \Phplrt\Contracts\Parser\ParserInterface $parser;

    protected readonly \Phplrt\Contracts\Lexer\LexerInterface $lexer;

    public function __construct()
    {
        $state_php = new \Phplrt\Compiler\Syntax\Common\PhpBlockLexer();
        $state_declaration = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\h++)(*MARK:0))|(?:(?:->\\h*+[a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\(\\h*+(?:[a-zA-Z_][a-zA-Z0-9_]*+)?\\h*+\\)(?:\\h*+,\\h*+[a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\(\\h*+(?:[a-zA-Z_][a-zA-Z0-9_]*+)?\\h*+\\))*+)(*MARK:1))|(?:(?:(?:[a-zA-Z_][a-zA-Z0-9_]*+|\\*):)(*MARK:2))|(?:(?:[a-zA-Z_][a-zA-Z0-9_]*+(?=\\h++(?!->\\h*+[a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\()(?![\\r\\n])(?!$)))(*MARK:3))|(?:(?:\\S++)(*MARK:4))|(?:(?:\\R)(*MARK:5))|(?:(?:[^\\s]++)(*MARK:6)))/Ssum',
            channels: [
                'Hidden',
                6 => 'Unknown',
            ],
            names: [
                'T_HORIZONTAL_SPACE',
                'T_ACTIONS',
                'T_STATE',
                'T_NAME',
                'T_PATTERN',
                'T_END',
            ],
            transitions: [
                5 => null,
            ],
        );

        $this->lexer = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:\\/\\/[^\\r\\n]*+)(*MARK:1))|(?:(?:\\/\\*(.*?)\\*\\/)(*MARK:2))|(?:(?:%pragma\\h++([a-zA-Z_][a-zA-Z0-9_.]*+)\\h++(\\S++))(*MARK:3))|(?:(?:%include\\h++(\\S++))(*MARK:4))|(?:(?:->\\s*+(?=\\{))(*MARK:5))|(?:(?:@([a-zA-Z_][a-zA-Z0-9_]*+))(*MARK:6))|(?:(?:;)(*MARK:7))|(?:(?:\\|)(*MARK:8))|(?:(?:\\()(*MARK:9))|(?:(?:\\))(*MARK:10))|(?:(?:<)(*MARK:11))|(?:(?:>)(*MARK:12))|(?:(?:\\?)(*MARK:13))|(?:(?:\\+)(*MARK:14))|(?:(?:\\*)(*MARK:15))|(?:(?:\\{)(*MARK:16))|(?:(?:\\})(*MARK:17))|(?:(?:,)(*MARK:18))|(?:(?:\\d++)(*MARK:19))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:20))|(?:(?:\\\\?+[a-zA-Z_][a-zA-Z0-9_]*+(?:\\\\[a-zA-Z_][a-zA-Z0-9_]*+)*+)(*MARK:21))|(?:(?:%token(?=\\h))(*MARK:22))|(?:(?:%skip(?=\\h))(*MARK:23))|(?:(?:%fragment(?=\\h))(*MARK:24))|(?:(?:%lexer\\h++([a-zA-Z_][a-zA-Z0-9_]*+))(*MARK:25))|(?:(?:::)(*MARK:26))|(?:(?::)(*MARK:27))|(?:(?:&)(*MARK:28))|(?:(?:!)(*MARK:29))|(?:(?:\\/([^\\/\\\\]*+(?:\\\\.[^\\/\\\\]*+)*+)\\/)(*MARK:30))|(?:(?:[^\\s]++)(*MARK:31)))/Ssum',
            channels: [
                'Hidden',
                'Hidden',
                'doc',
                31 => 'Unknown',
            ],
            names: [
                'T_WHITESPACE',
                'T_COMMENT',
                'T_DOC',
                'T_PRAGMA',
                'T_INCLUDE',
                'T_PHP',
                'T_ANNOTATION',
                'T_SEMICOLON',
                'T_OR',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_ANGLE_OPEN',
                'T_ANGLE_CLOSE',
                'T_QUESTION_MARK',
                'T_PLUS',
                'T_ASTERISK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_COMMA',
                'T_INT',
                'T_STRING',
                'T_NAME',
                'T_TOKEN',
                'T_SKIP',
                'T_FRAGMENT',
                'T_LEXER',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_AMPERSAND',
                'T_EXCLAMATION',
                'T_REGEX',
            ],
            transitions: [
                5 => $state_php,
                22 => $state_declaration,
                23 => $state_declaration,
                24 => $state_declaration,
            ],
            subgroups: [
                2 => 1,
                2,
                1,
                6 => 1,
                25 => 1,
                30 => 1,
            ],
        );

        $this->parser = new \Phplrt\Parser\Parser(
            lexer: $this->lexer,
            grammar: [
                new \Phplrt\Parser\Grammar\Concatenation([1, 69]),
                new \Phplrt\Parser\Grammar\Repetition(2, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([3, 5]),
                new \Phplrt\Parser\Grammar\Repetition(4, 0, \INF),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOC, true),
                new \Phplrt\Parser\Grammar\Alternation([6, 9, 10, 11, 12, 15]),
                new \Phplrt\Parser\Grammar\Alternation([7, 8]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TOKEN, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SKIP, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FRAGMENT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PRAGMA, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INCLUDE, true),
                new \Phplrt\Parser\Grammar\Concatenation([13, 14]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_LEXER, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PHP, true),
                new \Phplrt\Parser\Grammar\Concatenation([16, 17, 29, 30, 31, 67]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Optional(18),
                new \Phplrt\Parser\Grammar\Repetition(19, 1, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([20, 21, 22, 28]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANNOTATION, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Optional(23),
                new \Phplrt\Parser\Grammar\Concatenation([24, 25]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_STRING, true),
                new \Phplrt\Parser\Grammar\Repetition(26, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([27, 24]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Optional(14),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([32, 64]),
                new \Phplrt\Parser\Grammar\Repetition(33, 1, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([34, 38, 17]),
                new \Phplrt\Parser\Grammar\Optional(35),
                new \Phplrt\Parser\Grammar\Alternation([36, 37]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMPERSAND, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EXCLAMATION, true),
                new \Phplrt\Parser\Grammar\Concatenation([39, 50]),
                new \Phplrt\Parser\Grammar\Alternation([40, 41, 44, 46, 47]),
                new \Phplrt\Parser\Grammar\Concatenation([21, 31, 28]),
                new \Phplrt\Parser\Grammar\Concatenation([42, 16, 43]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([45, 16, 45]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([16, 21, 28]),
                new \Phplrt\Parser\Grammar\Alternation([48, 49]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_STRING, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_REGEX, true),
                new \Phplrt\Parser\Grammar\Optional(51),
                new \Phplrt\Parser\Grammar\Alternation([52, 53, 54, 55]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QUESTION_MARK, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PLUS, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Concatenation([56, 57, 63]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([58, 60, 61, 62]),
                new \Phplrt\Parser\Grammar\Concatenation([59, 27, 59]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INT, true),
                new \Phplrt\Parser\Grammar\Concatenation([59, 27]),
                new \Phplrt\Parser\Grammar\Concatenation([27, 59]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(65, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([66, 32]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
                new \Phplrt\Parser\Grammar\Optional(68),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SEMICOLON, false),
                new \Phplrt\Parser\Grammar\Repetition(70, 0, \INF),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOC, false),
            ],
            initial: 0,
            reducers: [
                2 => self::reduceDeclaration(...),
                6 => self::reduceTokenDeclaration(...),
                9 => self::reduceFragmentDeclaration(...),
                10 => self::reducePragmaDeclaration(...),
                11 => self::reduceIncludeDeclaration(...),
                12 => self::reduceLexerDeclaration(...),
                14 => self::reduceCodeReducer(...),
                15 => self::reduceRuleDeclaration(...),
                19 => self::reduceAnnotation(...),
                31 => self::reduceAlternation(...),
                32 => self::reduceConcatenation(...),
                33 => self::reduceElement(...),
                38 => self::reduceSuffixed(...),
                41 => self::reduceKeptTokenReference(...),
                44 => self::reduceSkippedTokenReference(...),
                46 => self::reduceRuleReference(...),
                48 => self::reduceInlineValue(...),
                49 => self::reduceInlinePattern(...),
                52 => self::reduceZeroOrOne(...),
                53 => self::reduceOneOrMore(...),
                54 => self::reduceZeroOrMore(...),
                58 => self::reduceRangeFromTo(...),
                60 => self::reduceRangeFrom(...),
                61 => self::reduceRangeTo(...),
                62 => self::reduceRangeExactly(...),
            ],
            lookahead: [
                null,
                null,
                [
                    2 => true,
                    true,
                    true,
                    21 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                null,
                [
                    2 => true,
                ],
                [
                    3 => true,
                    true,
                    21 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                [
                    22 => true,
                    true,
                ],
                [
                    22 => true,
                ],
                [
                    23 => true,
                ],
                [
                    24 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    25 => true,
                ],
                [
                    25 => true,
                ],
                [
                    5 => true,
                ],
                [
                    21 => true,
                ],
                [
                    21 => true,
                ],
                null,
                [
                    6 => true,
                ],
                [
                    6 => true,
                ],
                [
                    6 => true,
                ],
                [
                    9 => true,
                ],
                null,
                [
                    20 => true,
                ],
                [
                    20 => true,
                ],
                null,
                [
                    18 => true,
                ],
                [
                    18 => true,
                ],
                [
                    10 => true,
                ],
                null,
                [
                    27 => true,
                ],
                [
                    9 => true,
                    11 => true,
                    20 => true,
                    true,
                    26 => true,
                    28 => true,
                    true,
                    true,
                ],
                [
                    9 => true,
                    11 => true,
                    20 => true,
                    true,
                    26 => true,
                    28 => true,
                    true,
                    true,
                ],
                [
                    9 => true,
                    11 => true,
                    20 => true,
                    true,
                    26 => true,
                    28 => true,
                    true,
                    true,
                ],
                null,
                [
                    28 => true,
                    true,
                ],
                [
                    28 => true,
                ],
                [
                    29 => true,
                ],
                [
                    9 => true,
                    11 => true,
                    20 => true,
                    true,
                    26 => true,
                    30 => true,
                ],
                [
                    9 => true,
                    11 => true,
                    20 => true,
                    true,
                    26 => true,
                    30 => true,
                ],
                [
                    9 => true,
                ],
                [
                    11 => true,
                ],
                [
                    11 => true,
                ],
                [
                    12 => true,
                ],
                [
                    26 => true,
                ],
                [
                    26 => true,
                ],
                [
                    21 => true,
                ],
                [
                    20 => true,
                    30 => true,
                ],
                [
                    20 => true,
                ],
                [
                    30 => true,
                ],
                null,
                [
                    13 => true,
                    true,
                    true,
                    true,
                ],
                [
                    13 => true,
                ],
                [
                    14 => true,
                ],
                [
                    15 => true,
                ],
                [
                    16 => true,
                ],
                [
                    16 => true,
                ],
                [
                    18 => true,
                    true,
                ],
                [
                    19 => true,
                ],
                [
                    19 => true,
                ],
                [
                    19 => true,
                ],
                [
                    18 => true,
                ],
                [
                    19 => true,
                ],
                [
                    17 => true,
                ],
                null,
                [
                    8 => true,
                ],
                [
                    8 => true,
                ],
                null,
                [
                    7 => true,
                ],
                null,
                [
                    2 => true,
                ],
            ],
            kept: [
                true,
                false,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                true,
                true,
                true,
                false,
                true,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                true,
                false,
                true,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                true,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
            ],
            choicePrediction: [
                5 => [
                    22 => [
                        6,
                    ],
                    [
                        6,
                    ],
                    [
                        9,
                    ],
                    3 => [
                        10,
                    ],
                    4 => [
                        11,
                    ],
                    [
                        12,
                    ],
                    21 => [
                        15,
                    ],
                ],
                [
                    22 => [
                        7,
                    ],
                    [
                        8,
                    ],
                ],
                35 => [
                    28 => [
                        36,
                    ],
                    [
                        37,
                    ],
                ],
                39 => [
                    9 => [
                        40,
                    ],
                    11 => [
                        41,
                    ],
                    26 => [
                        44,
                    ],
                    21 => [
                        46,
                    ],
                    20 => [
                        47,
                    ],
                    30 => [
                        47,
                    ],
                ],
                47 => [
                    20 => [
                        48,
                    ],
                    30 => [
                        49,
                    ],
                ],
                51 => [
                    13 => [
                        52,
                    ],
                    [
                        53,
                    ],
                    [
                        54,
                    ],
                    [
                        55,
                    ],
                ],
                57 => [
                    19 => [
                        58,
                        60,
                        62,
                    ],
                    18 => [
                        61,
                    ],
                ],
            ],
            expectations: [
                'T_WHITESPACE',
                'T_COMMENT',
                'T_DOC',
                'T_PRAGMA',
                'T_INCLUDE',
                'T_PHP',
                'T_ANNOTATION',
                'T_SEMICOLON',
                'T_OR',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_ANGLE_OPEN',
                'T_ANGLE_CLOSE',
                'T_QUESTION_MARK',
                'T_PLUS',
                'T_ASTERISK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_COMMA',
                'T_INT',
                'T_STRING',
                'T_NAME',
                'T_TOKEN',
                'T_SKIP',
                'T_FRAGMENT',
                'T_LEXER',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_AMPERSAND',
                'T_EXCLAMATION',
                'T_REGEX',
                '/[^\\s]++/',
            ],
        );
    }

    public function parse(\Phplrt\Contracts\Source\ReadableInterface $source): mixed
    {
        return $this->parser->parse($source);
    }

    /**
     * A single element of a grammar file, along with what is written about it.
     *
     *  A comment is read rather than thrown away, so it arrives here together with
     *  the element it stands before. Whether it is written about that element is
     *  decided by the empty line PHP decides it by: a comment written right before
     *  an element is written about it, and a comment written a line away from one
     *  is written about the file it stands in.
     *
     *  Several comments may stand before a single element, and only the last of
     *  them stands right before it.
     */
    private static function reduceDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $content = $ctx->source->content;
        $end = $ctx->begin + $ctx->length;

        \assert(\is_array($children));

        $declaration = \array_pop($children);
        $comment = \array_pop($children);

        \assert($declaration instanceof \Phplrt\Compiler\Node\Declaration\Declaration);

        if ($comment === null) {
            return $declaration;
        }

        \assert($comment instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($comment->value !== '', 'The lexer never produces an empty token');

        $end = $comment->offset + $comment->size;
        $between = \substr($content, $end, \max(0, $declaration->offset - $end));

        if (\preg_match('/\R\h*+\R/', $between) === 1) {
            return $declaration;
        }

        return $declaration->setComment($comment->value);
    }

    /**
     * A token to read, like:
     *  - %token string:T_QUOTE " -> state(string), channel(strings)
     *  - %skip *:T_WHITESPACE \s++
     *
     *  The declaration is read by a lexer of its own, so it arrives here as the
     *  parts it is written of rather than as a single value: the state the token
     *  belongs to, its name, the expression recognizing it and everything it does
     *  to the reading. Each of them is a token, so each of them is pointed at by
     *  the place it is written at.
     *
     *  A token that is read but never reaches the parser is declared with "%skip"
     *  instead of "%token", and nothing else about it differs.
     *
     *  Everything the token does is read as a single part, because a lexer reading
     *  one action at a time could not tell an action from an expression spelled
     *  like one. They are told apart here.
     */
    private static function reduceTokenDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\TokenEmbedding);

        $state = null;
        $name = null;
        $pattern = null;
        $actions = [];

        foreach ($children->children as $part) {
            // A declaration is written of each part at most once, so anything
            // written twice is pointed at where it is written
            switch ($part->name) {
                case 'T_STATE':
                    if ($state !== null) {
                        throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
                    }

                    $state = \substr($part->value, 0, -1);

                    break;

                case 'T_NAME':
                    if ($name !== null) {
                        throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
                    }

                    $name = $part->value;

                    break;

                case 'T_PATTERN':
                    if ($pattern !== null) {
                        throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
                    }

                    $pattern = $part->value;

                    break;

                case 'T_ACTIONS':
                    if ($actions !== []) {
                        throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
                    }

                    \preg_match_all(
                        pattern: '/([a-zA-Z_][a-zA-Z0-9_]*+)\h*+\(\h*+([a-zA-Z_][a-zA-Z0-9_]*+)?\h*+\)/',
                        subject: $part->value,
                        matches: $matches,
                        flags: \PREG_SET_ORDER | \PREG_OFFSET_CAPTURE,
                    );

                    foreach ($matches as $match) {
                        [$action, $at] = $match[0];

                        $argument = $match[2][0] ?? '';

                        $actions[] = new \Phplrt\Compiler\Node\Declaration\TokenAction(
                            name: $match[1][0],
                            argument: $argument === '' ? null : $argument,
                            offset: \max(0, $part->offset + $at),
                            length: \strlen($action),
                        );
                    }

                    break;
            }
        }

        // A declaration written of anything but a name and an expression describes
        // no token at all
        if ($name === null || $name === '' || $pattern === null || $pattern === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $children);
        }

        return new \Phplrt\Compiler\Node\Declaration\TokenDeclaration(
            name: $name,
            pattern: $pattern,
            state: $state === '' ? null : $state,
            isHidden: $children->value === '%skip',
            actions: $actions,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * A named piece of an expression, like:
     *  - %fragment DIGIT [0-9]
     *
     *  The declaration is read by the very lexer a token declaration is read by,
     *  so it arrives here as the same parts. A piece belongs to no state and does
     *  nothing to the reading, so the parts saying either of those are reported
     *  where they are written.
     */
    private static function reduceFragmentDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\TokenEmbedding);

        $name = null;
        $pattern = null;

        foreach ($children->children as $part) {
            switch ($part->name) {
                case 'T_NAME':
                    if ($name !== null) {
                        throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
                    }

                    $name = $part->value;

                    break;

                case 'T_PATTERN':
                    if ($pattern !== null) {
                        throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
                    }

                    $pattern = $part->value;

                    break;

                case 'T_STATE':
                case 'T_ACTIONS':
                    throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $part);
            }
        }

        // A declaration written of anything but a name and an expression describes
        // no piece at all
        if ($name === null || $name === '' || $pattern === null || $pattern === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $children);
        }

        return new \Phplrt\Compiler\Node\Declaration\FragmentDeclaration(
            name: $name,
            pattern: $pattern,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * A setting of the compilation, like:
     *  - %pragma root Expression
     *
     *  The name and the value are captured by the very token the directive is read
     *  as, and both of them have to be written for the directive to mean anything.
     */
    private static function reducePragmaDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $name = $children->captures[0] ?? '';
        $value = $children->captures[1] ?? '';

        if ($name === '' || $value === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $children);
        }

        return new \Phplrt\Compiler\Node\Declaration\PragmaDeclaration(
            name: $name,
            value: $value,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * Another grammar to read, like:
     *  - %include grammar/pp3/lexemes
     */
    private static function reduceIncludeDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $target = $children->captures[0] ?? '';

        if ($target === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $children);
        }

        return new \Phplrt\Compiler\Node\Declaration\IncludeDeclaration(
            target: $target,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * A lexer written by hand, like:
     *  - %lexer php -> { new \App\Lexer\PhpLexer() }
     *
     *  The body is an expression building the lexer rather than a block of
     *  statements, so it is read the way the body of a reducer is and is left for
     *  the compilation to make sense of.
     */
    private static function reduceLexerDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $declaration = $children[0] ?? null;
        $lexer = $children[1] ?? null;

        \assert($declaration instanceof \Phplrt\Lexer\Token\Token);
        \assert($lexer instanceof \Phplrt\Compiler\Node\Reducer\CodeReducer);

        $name = $declaration->captures[0] ?? '';

        if ($name === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::becauseUnexpectedTokenProduced($ctx->source, $declaration);
        }

        return new \Phplrt\Compiler\Node\Declaration\LexerDeclaration(
            name: $name,
            lexer: $lexer,
            offset: $declaration->offset,
            length: \max(0, $lexer->offset + $lexer->length - $declaration->offset),
        );
    }

    /**
     * A block of PHP code, like:
     *  - -> { return new SumNode($children); }
     *
     *  The code is read by a lexer of its own, so it arrives here as the tokens
     *  PHP has been read into rather than as a value: the braces surrounding it
     *  belong to the grammar rather than to the code, and are dropped by taking
     *  everything written between them.
     *
     *  What is left is taken out of the nesting the grammar has written it in. A
     *  body is read from the grammar file exactly as it is written there, so the
     *  nesting of the rule it belongs to is a part of it. The body is written into
     *  something else afterwards (a generated method, an evaluated callback) which
     *  nests it on its own, so a single level of nesting is taken away.
     *
     *  The line the body starts at is written after the brace opening it rather
     *  than on a line of its own, so whatever precedes it is not nesting at all.
     */
    private static function reduceCodeReducer(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\TokenEmbedding);

        $read = $children->children;
        $code = '';

        // Note: The braces are the first and the last of the tokens read, so
        //       everything between them is the code itself.
        for ($i = 1, $last = \count($read) - 1; $i < $last; ++$i) {
            $code .= $read[$i]->value;
        }

        $lines = \explode("\n", $code);

        foreach ($lines as $index => $line) {
            $lines[$index] = $index === 0
                ? \ltrim($line)
                : \preg_replace('/^ {1,4}/', '', $line);
        }

        return new \Phplrt\Compiler\Node\Reducer\CodeReducer(
            code: \trim(\implode("\n", $lines)),
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * A rule of the parser, like:
     *  - Sum -> { return new SumNode($children); } : Number() ;
     *
     *  The name is written first, the reducer after it and what the rule recognizes
     *  past the colon, so the declaration is read from both ends: whatever is left
     *  between them is the reducer, in case it has been written at all.
     *
     *  Whatever is said about the rule apart from what it recognizes is written
     *  after its name.
     */
    private static function reduceRuleDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $name = \array_shift($children);
        $body = \array_pop($children);

        $annotations = [];

        // What is said about the rule is written after its name, so it is read off
        // the front until the reducer is reached
        while (($annotation = $children[0] ?? null) instanceof \Phplrt\Compiler\Node\Annotation) {
            $annotations[] = $annotation;

            \array_shift($children);
        }

        $reducer = \array_pop($children);

        \assert($name instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($name->value !== '', 'The lexer never produces an empty token');
        \assert($body instanceof \Phplrt\Compiler\Node\Statement\Statement);
        \assert($reducer === null || $reducer instanceof \Phplrt\Compiler\Node\Reducer\Reducer);

        return new \Phplrt\Compiler\Node\Declaration\RuleDeclaration(
            name: $name->value,
            body: $body,
            reducer: $reducer,
            annotations: $annotations,
            offset: $name->offset,
            length: \max(0, $body->offset + $body->length - $name->offset),
        );
    }

    /**
     * A single thing said about a rule or about a statement, written as a name
     * along with the values it is said with.
     *
     * What a name means is decided by the compilation rather than here, so a name
     * it knows nothing about is still read.
     */
    private static function reduceAnnotation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $name = \array_shift($children);

        \assert($name instanceof \Phplrt\Lexer\Token\Token);

        // The "@" opening the annotation belongs to the grammar rather than to the
        // name, so the name is captured apart from it
        $identifier = $name->captures[0] ?? '';

        \assert($identifier !== '', 'The name is captured by the token the annotation is read as');

        $arguments = [];
        $last = $name;

        foreach ($children as $argument) {
            \assert($argument instanceof \Phplrt\Contracts\Lexer\TokenInterface);

            // The quotes surrounding a value belong to the grammar rather than to
            // the value, and a quote of the value is written escaped for the very
            // same reason
            $arguments[] = \str_replace('\\"', '"', \substr($argument->value, 1, -1));

            $last = $argument;
        }

        return new \Phplrt\Compiler\Node\Annotation(
            name: $identifier,
            arguments: $arguments,
            offset: $name->offset,
            length: \max(0, $last->offset + $last->size - $name->offset),
        );
    }

    /**
     * One of several things to recognize, like:
     *  - Number() | Name()
     *
     *  An alternative of a single statement is that statement: the choice a rule
     *  is written of is only a choice once there is something to choose from.
     */
    private static function reduceAlternation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $statements = [];

        foreach ($children as $statement) {
            \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

            $statements[] = $statement;
        }

        \assert($statements !== [], 'A production recognizes at least one statement');

        if (!isset($statements[1])) {
            return $statements[0];
        }

        $last = $statements[\count($statements) - 1];

        return new \Phplrt\Compiler\Node\Statement\Alternation(
            statements: $statements,
            offset: $statements[0]->offset,
            length: \max(0, $last->offset + $last->length - $statements[0]->offset),
        );
    }

    /**
     * Several things to recognize one after another, like:
     *  - Number() ::T_PLUS:: Number()
     *
     *  A sequence of a single statement is that statement, for the very same
     *  reason an alternative of one is.
     */
    private static function reduceConcatenation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $statements = [];

        foreach ($children as $statement) {
            \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

            $statements[] = $statement;
        }

        \assert($statements !== [], 'A production recognizes at least one statement');

        if (!isset($statements[1])) {
            return $statements[0];
        }

        $last = $statements[\count($statements) - 1];

        return new \Phplrt\Compiler\Node\Statement\Concatenation(
            statements: $statements,
            offset: $statements[0]->offset,
            length: \max(0, $last->offset + $last->length - $statements[0]->offset),
        );
    }

    /**
     * A single thing a sequence is written of, like:
     *  - `&<T_ELSE>`
     *  - `Number()*` with `@error("a number is expected")`
     *
     *  A statement may be looked ahead at, and it may be said something about
     *  apart from what it recognizes.
     *
     *  The statement of a predicate is recognized the way any other one is, and
     *  whatever it has read is given back afterwards: an "&" carries on when it
     *  has been recognized, a "!" when it has not, and neither of them ever
     *  reaches the syntax tree.
     *
     *  The predicate stands before the quantifier rather than after it, so
     *  "&Number()*" looks ahead at any number of them at once instead of looking
     *  ahead any number of times.
     *
     *  Whatever is said about the statement is written after the predicate, so it
     *  is said about the looking ahead rather than about what is looked ahead at.
     *
     *  A statement written with nothing around it is that statement.
     */
    private static function reduceElement(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $annotations = [];

        // What is said about the statement is written after it, so it is read off
        // the back until the statement itself is reached
        while (($annotation = $children[\count($children) - 1] ?? null) instanceof \Phplrt\Compiler\Node\Annotation) {
            \array_unshift($annotations, $annotation);

            \array_pop($children);
        }

        $sign = $children[0] ?? null;
        $statement = $children[1] ?? null;

        if ($statement === null) {
            \assert($sign instanceof \Phplrt\Compiler\Node\Statement\Statement);

            $statement = $sign;
        } else {
            \assert($sign instanceof \Phplrt\Contracts\Lexer\TokenInterface);
            \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

            $statement = new \Phplrt\Compiler\Node\Statement\Predicate(
                statement: $statement,
                isExpected: $sign->value === '&',
                offset: $sign->offset,
                length: \max(0, $statement->offset + $statement->length - $sign->offset),
            );
        }

        if ($annotations === []) {
            return $statement;
        }

        $last = $annotations[\count($annotations) - 1];

        return new \Phplrt\Compiler\Node\Statement\Annotated(
            statement: $statement,
            annotations: $annotations,
            offset: $statement->offset,
            length: \max(0, $last->offset + $last->length - $statement->offset),
        );
    }

    /**
     * A statement along with the number of times it may repeat, like:
     *  - Number()*
     *
     *  A statement written with no quantifier repeats exactly once, which is what
     *  the statement itself already means.
     */
    private static function reduceSuffixed(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $statement = $children[0] ?? null;
        $quantifier = $children[1] ?? null;

        \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

        if (!$quantifier instanceof \Phplrt\Compiler\Node\Statement\Quantifier) {
            return $statement;
        }

        return new \Phplrt\Compiler\Node\Statement\Repetition(
            statement: $statement,
            quantifier: $quantifier,
            offset: $statement->offset,
            length: \max(0, $quantifier->offset + $quantifier->length - $statement->offset),
        );
    }

    /**
     * A token whose value is kept in the syntax tree, like:
     *  - <T_NAME>
     */
    private static function reduceKeptTokenReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $name = $children[0] ?? null;

        \assert($name instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($name->value !== '', 'The lexer never produces an empty token');

        return new \Phplrt\Compiler\Node\Statement\TokenReference(
            name: $name->value,
            isKept: true,
            offset: $name->offset,
            length: $name->size,
        );
    }

    /**
     * A token that is read and thrown away, like:
     *  - ::T_COMMA::
     */
    private static function reduceSkippedTokenReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $name = $children[0] ?? null;

        \assert($name instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($name->value !== '', 'The lexer never produces an empty token');

        return new \Phplrt\Compiler\Node\Statement\TokenReference(
            name: $name->value,
            isKept: false,
            offset: $name->offset,
            length: $name->size,
        );
    }

    /**
     * Another rule to recognize, like:
     *  - Number()
     *
     *  The rule is pointed at by name: it may well be declared in a grammar that
     *  has not been read yet.
     */
    private static function reduceRuleReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $name = $children[0] ?? null;

        \assert($name instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($name->value !== '', 'The lexer never produces an empty token');

        return new \Phplrt\Compiler\Node\Statement\RuleReference(
            name: $name->value,
            offset: $name->offset,
            length: $name->size,
        );
    }

    /**
     * A token declared by the statement reading it, written as the text it
     * recognizes, like:
     *  - "+"
     *
     *  The text is read as it is written: whatever is special to a regular
     *  expression is only itself here, which is what makes this the shorter way of
     *  spelling the punctuation a language is held together by.
     *
     *  The quotes surrounding it belong to the grammar rather than to the text, and
     *  a quote of the text is written escaped for the very same reason.
     */
    private static function reduceInlineValue(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\InlineValue(
            value: \str_replace('\\"', '"', \substr($children->value, 1, -1)),
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * A token declared by the statement reading it, written as the expression
     * recognizing it, like:
     *  - /and|or|xor/
     *
     *  The slashes surrounding the expression belong to the grammar rather than to
     *  the expression itself, and a slash of the expression is written escaped for
     *  the very same reason.
     */
    private static function reduceInlinePattern(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\InlinePattern(
            pattern: \str_replace('\\/', '/', \substr($children->value, 1, -1)),
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * Never or once, like:
     *  - Number()?
     */
    private static function reduceZeroOrOne(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 0,
            max: 1,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * At least once, like:
     *  - Number()+
     */
    private static function reduceOneOrMore(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 1,
            max: \INF,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * Any number of times, like:
     *  - Number()*
     */
    private static function reduceZeroOrMore(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 0,
            max: \INF,
            offset: $children->offset,
            length: $children->size,
        );
    }

    /**
     * Between two numbers of times, like:
     *  - Number(){2,5}
     *
     *  The range is written by hand, so the greatest number may well be lower than
     *  the least one. Whether it makes sense is decided while the grammar is being
     *  compiled rather than while it is being read.
     */
    private static function reduceRangeFromTo(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $from = $children[0] ?? null;
        $to = $children[1] ?? null;

        \assert($from instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($to instanceof \Phplrt\Contracts\Lexer\TokenInterface);

        $min = (int) $from->value;
        $max = (int) $to->value;

        \assert($min >= 0 && $max >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: $min,
            max: $max,
            offset: $from->offset,
            length: \max(0, $to->offset + $to->size - $from->offset),
        );
    }

    /**
     * At least a number of times, like:
     *  - Number(){2,}
     */
    private static function reduceRangeFrom(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $from = $children[0] ?? null;

        \assert($from instanceof \Phplrt\Contracts\Lexer\TokenInterface);

        $min = (int) $from->value;

        \assert($min >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: $min,
            max: \INF,
            offset: $from->offset,
            length: $from->size,
        );
    }

    /**
     * At most a number of times, like:
     *  - Number(){,5}
     */
    private static function reduceRangeTo(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $to = $children[0] ?? null;

        \assert($to instanceof \Phplrt\Contracts\Lexer\TokenInterface);

        $max = (int) $to->value;

        \assert($max >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 0,
            max: $max,
            offset: $to->offset,
            length: $to->size,
        );
    }

    /**
     * Exactly a number of times, like:
     *  - Number(){5}
     */
    private static function reduceRangeExactly(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $count = (int) $children->value;

        \assert($count >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: $count,
            max: $count,
            offset: $children->offset,
            length: $children->size,
        );
    }
}
