<?php

declare(strict_types=1);

namespace Phplrt\Compiler\Syntax\PP3;

/**
 * @internal This code has been generated by the phplrt compiler and should not
 *           be edited by hand
 */
readonly class PP3Parser extends \Phplrt\Parser\Parser
{
    public const int T_WHITESPACE = 0;
    public const int T_COMMENT = 1;
    public const int T_DOC = 2;
    public const int T_PRAGMA = 3;
    public const int T_INCLUDE = 4;
    public const int T_PHP = 5;
    public const int T_SEMICOLON = 6;
    public const int T_OR = 7;
    public const int T_PARENTHESIS_OPEN = 8;
    public const int T_PARENTHESIS_CLOSE = 9;
    public const int T_ANGLE_OPEN = 10;
    public const int T_ANGLE_CLOSE = 11;
    public const int T_QUESTION_MARK = 12;
    public const int T_PLUS = 13;
    public const int T_ASTERISK = 14;
    public const int T_BRACE_OPEN = 15;
    public const int T_BRACE_CLOSE = 16;
    public const int T_COMMA = 17;
    public const int T_INT = 18;
    public const int T_STRING = 19;
    public const int T_NAME = 20;
    public const int T_TOKEN = 21;
    public const int T_SKIP = 22;
    public const int T_LEXER = 23;
    public const int T_DOUBLE_COLON = 24;
    public const int T_COLON = 25;
    public const int T_AMPERSAND = 26;
    public const int T_EXCLAMATION = 27;

    public function __construct()
    {
        $state_php = new \Phplrt\Compiler\Syntax\Common\PhpBlockLexer();

        parent::__construct(
            lexer: new \Phplrt\Lexer\Lexer(
                pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:\\/\\/[^\\r\\n]*+)(*MARK:1))|(?:(?:\\/\\*(.*?)\\*\\/)(*MARK:2))|(?:(?:%pragma\\h++([a-zA-Z_][a-zA-Z0-9_.]*+)\\h++(\\S++))(*MARK:3))|(?:(?:%include\\h++(\\S++))(*MARK:4))|(?:(?:->\\s*+(?=\\{))(*MARK:5))|(?:(?:;)(*MARK:6))|(?:(?:\\|)(*MARK:7))|(?:(?:\\()(*MARK:8))|(?:(?:\\))(*MARK:9))|(?:(?:<)(*MARK:10))|(?:(?:>)(*MARK:11))|(?:(?:\\?)(*MARK:12))|(?:(?:\\+)(*MARK:13))|(?:(?:\\*)(*MARK:14))|(?:(?:\\{)(*MARK:15))|(?:(?:\\})(*MARK:16))|(?:(?:,)(*MARK:17))|(?:(?:\\d++)(*MARK:18))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:19))|(?:(?:\\\\?+[a-zA-Z_][a-zA-Z0-9_]*+(?:\\\\[a-zA-Z_][a-zA-Z0-9_]*+)*+)(*MARK:20))|(?:(?:%token\\h++(?:([a-zA-Z_][a-zA-Z0-9_]*+|\\*):)?([a-zA-Z_][a-zA-Z0-9_]*+)\\h++(\\S++)(?:\\h++->\\h*+([a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\(\\h*+(?:[a-zA-Z_][a-zA-Z0-9_]*+)?\\h*+\\)(?:\\h*+,\\h*+[a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\(\\h*+(?:[a-zA-Z_][a-zA-Z0-9_]*+)?\\h*+\\))*+))?)(*MARK:21))|(?:(?:%skip\\h++(?:([a-zA-Z_][a-zA-Z0-9_]*+|\\*):)?([a-zA-Z_][a-zA-Z0-9_]*+)\\h++(\\S++)(?:\\h++->\\h*+([a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\(\\h*+(?:[a-zA-Z_][a-zA-Z0-9_]*+)?\\h*+\\)(?:\\h*+,\\h*+[a-zA-Z_][a-zA-Z0-9_]*+\\h*+\\(\\h*+(?:[a-zA-Z_][a-zA-Z0-9_]*+)?\\h*+\\))*+))?)(*MARK:22))|(?:(?:%lexer\\h++([a-zA-Z_][a-zA-Z0-9_]*+))(*MARK:23))|(?:(?:::)(*MARK:24))|(?:(?::)(*MARK:25))|(?:(?:&)(*MARK:26))|(?:(?:!)(*MARK:27))|(?:(?:[^\\s]++)(*MARK:28)))/Ssum',
                channels: [
                    'Hidden',
                    'Hidden',
                    'Hidden',
                    28 => 'Unknown',
                ],
                names: [
                    'T_WHITESPACE',
                    'T_COMMENT',
                    'T_DOC',
                    'T_PRAGMA',
                    'T_INCLUDE',
                    'T_PHP',
                    'T_SEMICOLON',
                    'T_OR',
                    'T_PARENTHESIS_OPEN',
                    'T_PARENTHESIS_CLOSE',
                    'T_ANGLE_OPEN',
                    'T_ANGLE_CLOSE',
                    'T_QUESTION_MARK',
                    'T_PLUS',
                    'T_ASTERISK',
                    'T_BRACE_OPEN',
                    'T_BRACE_CLOSE',
                    'T_COMMA',
                    'T_INT',
                    'T_STRING',
                    'T_NAME',
                    'T_TOKEN',
                    'T_SKIP',
                    'T_LEXER',
                    'T_DOUBLE_COLON',
                    'T_COLON',
                    'T_AMPERSAND',
                    'T_EXCLAMATION',
                ],
                transitions: [
                    5 => $state_php,
                ],
                subgroups: [
                    2 => 1,
                    2,
                    1,
                    21 => 4,
                    4,
                    1,
                ],
            ),
            grammar: [
                new \Phplrt\Parser\Grammar\Repetition(1, 0, \INF),
                new \Phplrt\Parser\Grammar\Alternation([2, 5, 6, 7, 10]),
                new \Phplrt\Parser\Grammar\Alternation([3, 4]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TOKEN, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SKIP, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PRAGMA, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INCLUDE, true),
                new \Phplrt\Parser\Grammar\Concatenation([8, 9]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_LEXER, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PHP, true),
                new \Phplrt\Parser\Grammar\Concatenation([11, 12, 13, 14, 51]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Optional(9),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([15, 48]),
                new \Phplrt\Parser\Grammar\Repetition(16, 1, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([17, 21]),
                new \Phplrt\Parser\Grammar\Optional(18),
                new \Phplrt\Parser\Grammar\Alternation([19, 20]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMPERSAND, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EXCLAMATION, true),
                new \Phplrt\Parser\Grammar\Concatenation([22, 33]),
                new \Phplrt\Parser\Grammar\Alternation([23, 26, 29, 31, 32]),
                new \Phplrt\Parser\Grammar\Concatenation([24, 14, 25]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([27, 11, 28]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([30, 11, 30]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([11, 24, 25]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_STRING, true),
                new \Phplrt\Parser\Grammar\Optional(34),
                new \Phplrt\Parser\Grammar\Alternation([35, 36, 37, 38]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QUESTION_MARK, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PLUS, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Concatenation([39, 40, 47]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([41, 44, 45, 46]),
                new \Phplrt\Parser\Grammar\Concatenation([42, 43, 42]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Concatenation([42, 43]),
                new \Phplrt\Parser\Grammar\Concatenation([43, 42]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(49, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([50, 15]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
                new \Phplrt\Parser\Grammar\Optional(52),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SEMICOLON, false),
            ],
            initial: 0,
            reducers: [
                2 => self::reduceTokenDeclaration(...),
                5 => self::reducePragmaDeclaration(...),
                6 => self::reduceIncludeDeclaration(...),
                7 => self::reduceLexerDeclaration(...),
                9 => self::reduceCodeReducer(...),
                10 => self::reduceRuleDeclaration(...),
                14 => self::reduceAlternation(...),
                15 => self::reduceConcatenation(...),
                16 => self::reducePrefixed(...),
                21 => self::reduceSuffixed(...),
                26 => self::reduceKeptTokenReference(...),
                29 => self::reduceSkippedTokenReference(...),
                31 => self::reduceRuleReference(...),
                32 => self::reduceInlinePattern(...),
                35 => self::reduceZeroOrOne(...),
                36 => self::reduceOneOrMore(...),
                37 => self::reduceZeroOrMore(...),
                41 => self::reduceRangeFromTo(...),
                44 => self::reduceRangeFrom(...),
                45 => self::reduceRangeTo(...),
                46 => self::reduceRangeExactly(...),
            ],
            startTokens: [
                [
                    3 => true,
                    true,
                    20 => true,
                    true,
                    true,
                    true,
                ],
                [
                    3 => true,
                    true,
                    20 => true,
                    true,
                    true,
                    true,
                ],
                [
                    21 => true,
                    true,
                ],
                [
                    21 => true,
                ],
                [
                    22 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    23 => true,
                ],
                [
                    23 => true,
                ],
                [
                    5 => true,
                ],
                [
                    20 => true,
                ],
                [
                    20 => true,
                ],
                [
                    5 => true,
                ],
                [
                    25 => true,
                ],
                [
                    8 => true,
                    10 => true,
                    19 => true,
                    true,
                    24 => true,
                    26 => true,
                    true,
                ],
                [
                    8 => true,
                    10 => true,
                    19 => true,
                    true,
                    24 => true,
                    26 => true,
                    true,
                ],
                [
                    8 => true,
                    10 => true,
                    19 => true,
                    true,
                    24 => true,
                    26 => true,
                    true,
                ],
                [
                    26 => true,
                    true,
                ],
                [
                    26 => true,
                    true,
                ],
                [
                    26 => true,
                ],
                [
                    27 => true,
                ],
                [
                    8 => true,
                    10 => true,
                    19 => true,
                    true,
                    24 => true,
                ],
                [
                    8 => true,
                    10 => true,
                    19 => true,
                    true,
                    24 => true,
                ],
                [
                    8 => true,
                ],
                [
                    8 => true,
                ],
                [
                    9 => true,
                ],
                [
                    10 => true,
                ],
                [
                    10 => true,
                ],
                [
                    11 => true,
                ],
                [
                    24 => true,
                ],
                [
                    24 => true,
                ],
                [
                    20 => true,
                ],
                [
                    19 => true,
                ],
                [
                    12 => true,
                    true,
                    true,
                    true,
                ],
                [
                    12 => true,
                    true,
                    true,
                    true,
                ],
                [
                    12 => true,
                ],
                [
                    13 => true,
                ],
                [
                    14 => true,
                ],
                [
                    15 => true,
                ],
                [
                    15 => true,
                ],
                [
                    17 => true,
                    true,
                ],
                [
                    18 => true,
                ],
                [
                    18 => true,
                ],
                [
                    17 => true,
                ],
                [
                    18 => true,
                ],
                [
                    17 => true,
                ],
                [
                    18 => true,
                ],
                [
                    16 => true,
                ],
                [
                    7 => true,
                ],
                [
                    7 => true,
                ],
                [
                    7 => true,
                ],
                [
                    6 => true,
                ],
                [
                    6 => true,
                ],
            ],
            matchesEmptyInput: [
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
            ],
            presentInTree: [
                true,
                false,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                true,
                true,
                false,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                true,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
            ],
        );
    }

    private static function reduceTokenDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $name = $children->captures[1] ?? '';
        $pattern = $children->captures[2] ?? '';

        if ($name === '' || $pattern === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::fromToken($ctx->source, $children);
        }

        $state = $children->captures[0] ?? '';
        $actions = [];

        if (($children->captures[3] ?? '') !== '') {
            $arrow = \strrpos($children->value, '->');

            // A declaration carrying an action is always written of an arrow, so
            // the declaration itself is only pointed at in theory
            $start = $arrow === false ? 0 : $arrow;

            \preg_match_all(
                pattern: '/([a-zA-Z_][a-zA-Z0-9_]*+)\h*+\(\h*+([a-zA-Z_][a-zA-Z0-9_]*+)?\h*+\)/',
                subject: \substr($children->value, $start),
                matches: $matches,
                flags: \PREG_SET_ORDER | \PREG_OFFSET_CAPTURE,
            );

            foreach ($matches as $match) {
                [$action, $at] = $match[0];

                $word = $match[1][0];
                $argument = $match[2][0] ?? '';

                $actions[] = new \Phplrt\Compiler\Node\Declaration\TokenAction(
                    name: $word,
                    argument: $argument === '' ? null : $argument,
                    offset: \max(0, $children->offset + $start + $at),
                    length: \strlen($action),
                );
            }
        }

        return new \Phplrt\Compiler\Node\Declaration\TokenDeclaration(
            name: $name,
            pattern: $pattern,
            state: $state === '' ? null : $state,
            isHidden: \str_starts_with($children->value, '%skip'),
            actions: $actions,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reducePragmaDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $name = $children->captures[0] ?? '';
        $value = $children->captures[1] ?? '';

        if ($name === '' || $value === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::fromToken($ctx->source, $children);
        }

        return new \Phplrt\Compiler\Node\Declaration\PragmaDeclaration(
            name: $name,
            value: $value,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceIncludeDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $target = $children->captures[0] ?? '';

        if ($target === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::fromToken($ctx->source, $children);
        }

        return new \Phplrt\Compiler\Node\Declaration\IncludeDeclaration(
            target: $target,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceLexerDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $declaration = $children[0] ?? null;
        $lexer = $children[1] ?? null;

        \assert($declaration instanceof \Phplrt\Lexer\Token\Token);
        \assert($lexer instanceof \Phplrt\Compiler\Node\Reducer\CodeReducer);

        $name = $declaration->captures[0] ?? '';

        if ($name === '') {
            throw \Phplrt\Parser\Exception\UnexpectedTokenException::fromToken($ctx->source, $declaration);
        }

        return new \Phplrt\Compiler\Node\Declaration\LexerDeclaration(
            name: $name,
            lexer: $lexer,
            offset: $declaration->offset,
            length: \max(0, $lexer->offset + $lexer->length - $declaration->offset),
        );
    }

    private static function reduceCodeReducer(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\TokenEmbedding);

        $read = $children->children;
        $open = $read[0] ?? null;
        $close = $read[\count($read) - 1] ?? null;

        $code = $open === null || $close === null
            ? ''
            : \substr($ctx->content, $open->end, $close->offset - $open->end);

        $lines = \explode("\n", $code);

        foreach ($lines as $index => $line) {
            $lines[$index] = $index === 0
                ? \ltrim($line)
                : \preg_replace('/^ {1,4}/', '', $line);
        }

        return new \Phplrt\Compiler\Node\Reducer\CodeReducer(
            code: \trim(\implode("\n", $lines)),
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceRuleDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $name = \array_shift($children);
        $body = \array_pop($children);
        $reducer = \array_pop($children);

        \assert($name instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($name->value !== '', 'The lexer never produces an empty token');
        \assert($body instanceof \Phplrt\Compiler\Node\Statement\Statement);
        \assert($reducer === null || $reducer instanceof \Phplrt\Compiler\Node\Reducer\Reducer);

        return new \Phplrt\Compiler\Node\Declaration\RuleDeclaration(
            name: $name->value,
            body: $body,
            reducer: $reducer,
            offset: $name->offset,
            length: \max(0, $body->offset + $body->length - $name->offset),
        );
    }

    private static function reduceAlternation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $statements = [];

        foreach ($children as $statement) {
            \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

            $statements[] = $statement;
        }

        \assert($statements !== [], 'A production recognizes at least one statement');

        if (!isset($statements[1])) {
            return $statements[0];
        }

        $last = $statements[\count($statements) - 1];

        return new \Phplrt\Compiler\Node\Statement\Alternation(
            statements: $statements,
            offset: $statements[0]->offset,
            length: \max(0, $last->offset + $last->length - $statements[0]->offset),
        );
    }

    private static function reduceConcatenation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $statements = [];

        foreach ($children as $statement) {
            \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

            $statements[] = $statement;
        }

        \assert($statements !== [], 'A production recognizes at least one statement');

        if (!isset($statements[1])) {
            return $statements[0];
        }

        $last = $statements[\count($statements) - 1];

        return new \Phplrt\Compiler\Node\Statement\Concatenation(
            statements: $statements,
            offset: $statements[0]->offset,
            length: \max(0, $last->offset + $last->length - $statements[0]->offset),
        );
    }

    private static function reducePrefixed(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $sign = $children[0] ?? null;
        $statement = $children[1] ?? null;

        if ($statement === null) {
            \assert($sign instanceof \Phplrt\Compiler\Node\Statement\Statement);

            return $sign;
        }

        \assert($sign instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

        return new \Phplrt\Compiler\Node\Statement\Predicate(
            statement: $statement,
            isExpected: $sign->value === '&',
            offset: $sign->offset,
            length: \max(0, $statement->offset + $statement->length - $sign->offset),
        );
    }

    private static function reduceSuffixed(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $statement = $children[0] ?? null;
        $quantifier = $children[1] ?? null;

        \assert($statement instanceof \Phplrt\Compiler\Node\Statement\Statement);

        if (!$quantifier instanceof \Phplrt\Compiler\Node\Statement\Quantifier) {
            return $statement;
        }

        return new \Phplrt\Compiler\Node\Statement\Repetition(
            statement: $statement,
            quantifier: $quantifier,
            offset: $statement->offset,
            length: \max(0, $quantifier->offset + $quantifier->length - $statement->offset),
        );
    }

    private static function reduceKeptTokenReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $token = $ctx->token;

        \assert(\is_array($children));

        $token = $children[0] ?? null;

        \assert($token instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($token->value !== '', 'The lexer never produces an empty token');

        return new \Phplrt\Compiler\Node\Statement\TokenReference(
            name: $token->value,
            isKept: true,
            offset: $token->offset,
            length: \max(0, $token->end - $token->offset),
        );
    }

    private static function reduceSkippedTokenReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $token = $ctx->token;

        \assert(\is_array($children));

        $token = $children[0] ?? null;

        \assert($token instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($token->value !== '', 'The lexer never produces an empty token');

        return new \Phplrt\Compiler\Node\Statement\TokenReference(
            name: $token->value,
            isKept: false,
            offset: $token->offset,
            length: \max(0, $token->end - $token->offset),
        );
    }

    private static function reduceRuleReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $token = $ctx->token;

        \assert(\is_array($children));

        $token = $children[0] ?? null;

        \assert($token instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($token->value !== '', 'The lexer never produces an empty token');

        return new \Phplrt\Compiler\Node\Statement\RuleReference(
            name: $token->value,
            offset: $token->offset,
            length: \max(0, $token->end - $token->offset),
        );
    }

    private static function reduceInlinePattern(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\InlinePattern(
            pattern: \str_replace('\\"', '"', \substr($children->value, 1, -1)),
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceZeroOrOne(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 0,
            max: 1,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceOneOrMore(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 1,
            max: \INF,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceZeroOrMore(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 0,
            max: \INF,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }

    private static function reduceRangeFromTo(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $from = $children[0] ?? null;
        $to = $children[1] ?? null;

        \assert($from instanceof \Phplrt\Contracts\Lexer\TokenInterface);
        \assert($to instanceof \Phplrt\Contracts\Lexer\TokenInterface);

        $min = (int) $from->value;
        $max = (int) $to->value;

        \assert($min >= 0 && $max >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: $min,
            max: $max,
            offset: $from->offset,
            length: \max(0, $to->end - $from->offset),
        );
    }

    private static function reduceRangeFrom(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $from = $children[0] ?? null;

        \assert($from instanceof \Phplrt\Contracts\Lexer\TokenInterface);

        $min = (int) $from->value;

        \assert($min >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: $min,
            max: \INF,
            offset: $from->offset,
            length: \max(0, $from->end - $from->offset),
        );
    }

    private static function reduceRangeTo(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert(\is_array($children));

        $to = $children[0] ?? null;

        \assert($to instanceof \Phplrt\Contracts\Lexer\TokenInterface);

        $max = (int) $to->value;

        \assert($max >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: 0,
            max: $max,
            offset: $to->offset,
            length: \max(0, $to->end - $to->offset),
        );
    }

    private static function reduceRangeExactly(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        \assert($children instanceof \Phplrt\Lexer\Token\Token);

        $count = (int) $children->value;

        \assert($count >= 0, 'A number is written of digits only');

        return new \Phplrt\Compiler\Node\Statement\Quantifier(
            min: $count,
            max: $count,
            offset: $children->offset,
            length: \max(0, $children->end - $children->offset),
        );
    }
}
