<?php

declare(strict_types=1);

namespace Phplrt\Compiler\Syntax\PP2;

/**
 * @internal This code has been generated by the phplrt compiler and should not
 *           be edited by hand
 */
readonly class PP2Parser extends \Phplrt\Parser\Parser
{
    public const int T_WHITESPACE = 0;
    public const int T_COMMENT = 1;
    public const int T_DOC = 2;
    public const int T_TOKEN = 3;
    public const int T_SKIP = 4;
    public const int T_PRAGMA = 5;
    public const int T_INCLUDE = 6;
    public const int T_PHP = 7;
    public const int T_ARROW = 8;
    public const int T_DOUBLE_COLON = 9;
    public const int T_EQ = 10;
    public const int T_HASH = 11;
    public const int T_SEMICOLON = 12;
    public const int T_OR = 13;
    public const int T_PARENTHESIS_OPEN = 14;
    public const int T_PARENTHESIS_CLOSE = 15;
    public const int T_ANGLE_OPEN = 16;
    public const int T_ANGLE_CLOSE = 17;
    public const int T_QUESTION_MARK = 18;
    public const int T_PLUS = 19;
    public const int T_ASTERISK = 20;
    public const int T_BRACE_OPEN = 21;
    public const int T_BRACE_CLOSE = 22;
    public const int T_COMMA = 23;
    public const int T_INT = 24;
    public const int T_STRING = 25;
    public const int T_NAME = 26;

    public function __construct()
    {
        $state_php = new \Phplrt\Compiler\Syntax\PP2\PP2PhpEmbeddingLexer();

        parent::__construct(
            lexer: new \Phplrt\Lexer\Lexer(
                pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:\\/\\/[^\\r\\n]*+)(*MARK:1))|(?:(?:\\/\\*(.*?)\\*\\/)(*MARK:2))|(?:(?:%token\\h++(?:([a-zA-Z_][a-zA-Z0-9_]*+):)?([a-zA-Z_][a-zA-Z0-9_]*+)\\h++(\\S++)(?:\\h++->\\h*+(\\S++))?)(*MARK:3))|(?:(?:%skip\\h++(?:([a-zA-Z_][a-zA-Z0-9_]*+):)?([a-zA-Z_][a-zA-Z0-9_]*+)\\h++(\\S++)(?:\\h++->\\h*+(\\S++))?)(*MARK:4))|(?:(?:%pragma\\h++([a-zA-Z_][a-zA-Z0-9_.]*+)\\h++(\\S++))(*MARK:5))|(?:(?:%include\\h++(\\S++))(*MARK:6))|(?:(?:->\\s*+(?=\\{))(*MARK:7))|(?:(?:->)(*MARK:8))|(?:(?:::(?!=))(*MARK:9))|(?:(?:::=|:|=)(*MARK:10))|(?:(?:\\#)(*MARK:11))|(?:(?:;)(*MARK:12))|(?:(?:\\|)(*MARK:13))|(?:(?:\\()(*MARK:14))|(?:(?:\\))(*MARK:15))|(?:(?:<)(*MARK:16))|(?:(?:>)(*MARK:17))|(?:(?:\\?)(*MARK:18))|(?:(?:\\+)(*MARK:19))|(?:(?:\\*)(*MARK:20))|(?:(?:\\{)(*MARK:21))|(?:(?:\\})(*MARK:22))|(?:(?:,)(*MARK:23))|(?:(?:\\d++)(*MARK:24))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:25))|(?:(?:\\\\?+[a-zA-Z_][a-zA-Z0-9_]*+(?:\\\\[a-zA-Z_][a-zA-Z0-9_]*+)*+)(*MARK:26))|(?:(?:[^\\s]++)(*MARK:27)))/Ssum',
                channels: [
                    'Hidden',
                    'Hidden',
                    'Hidden',
                    27 => 'Unknown',
                ],
                names: [
                    'T_WHITESPACE',
                    'T_COMMENT',
                    'T_DOC',
                    'T_TOKEN',
                    'T_SKIP',
                    'T_PRAGMA',
                    'T_INCLUDE',
                    'T_PHP',
                    'T_ARROW',
                    'T_DOUBLE_COLON',
                    'T_EQ',
                    'T_HASH',
                    'T_SEMICOLON',
                    'T_OR',
                    'T_PARENTHESIS_OPEN',
                    'T_PARENTHESIS_CLOSE',
                    'T_ANGLE_OPEN',
                    'T_ANGLE_CLOSE',
                    'T_QUESTION_MARK',
                    'T_PLUS',
                    'T_ASTERISK',
                    'T_BRACE_OPEN',
                    'T_BRACE_CLOSE',
                    'T_COMMA',
                    'T_INT',
                    'T_STRING',
                    'T_NAME',
                ],
                transitions: [
                    7 => $state_php,
                ],
                subgroups: [
                    2 => 1,
                    4,
                    4,
                    2,
                    1,
                ],
            ),
            grammar: [
                new \Phplrt\Parser\Grammar\Repetition(1, 0, \INF),
                new \Phplrt\Parser\Grammar\Alternation([2, 3, 4, 5, 6]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TOKEN, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SKIP, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PRAGMA, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INCLUDE, true),
                new \Phplrt\Parser\Grammar\Concatenation([7, 9, 10, 15, 16, 48]),
                new \Phplrt\Parser\Grammar\Optional(8),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_HASH, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Optional(11),
                new \Phplrt\Parser\Grammar\Alternation([12, 13]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PHP, true),
                new \Phplrt\Parser\Grammar\Concatenation([14, 9]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ARROW, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EQ, false),
                new \Phplrt\Parser\Grammar\Concatenation([17, 45]),
                new \Phplrt\Parser\Grammar\Repetition(18, 1, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([19, 30]),
                new \Phplrt\Parser\Grammar\Alternation([20, 23, 26, 28, 29]),
                new \Phplrt\Parser\Grammar\Concatenation([21, 16, 22]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([24, 9, 25]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([27, 9, 27]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([9, 21, 22]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_STRING, true),
                new \Phplrt\Parser\Grammar\Optional(31),
                new \Phplrt\Parser\Grammar\Alternation([32, 33, 34, 35]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QUESTION_MARK, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PLUS, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Concatenation([36, 37, 44]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([38, 41, 42, 43]),
                new \Phplrt\Parser\Grammar\Concatenation([39, 40, 39]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Concatenation([39, 40]),
                new \Phplrt\Parser\Grammar\Concatenation([40, 39]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_INT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(46, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([47, 17]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, false),
                new \Phplrt\Parser\Grammar\Optional(49),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SEMICOLON, false),
            ],
            initial: 0,
            reducers: [
                2 => self::reduceTokenDeclaration(...),
                3 => self::reduceSkippedTokenDeclaration(...),
                4 => self::reducePragmaDeclaration(...),
                5 => self::reduceIncludeDeclaration(...),
                6 => self::reduceRuleDeclaration(...),
                8 => self::reduceKeptMarker(...),
                12 => self::reduceCodeReducer(...),
                13 => self::reduceClassReducer(...),
                16 => self::reduceAlternation(...),
                17 => self::reduceConcatenation(...),
                18 => self::reduceSuffixed(...),
                23 => self::reduceKeptTokenReference(...),
                26 => self::reduceSkippedTokenReference(...),
                28 => self::reduceRuleReference(...),
                29 => self::reduceInlinePattern(...),
                32 => self::reduceZeroOrOne(...),
                33 => self::reduceOneOrMore(...),
                34 => self::reduceZeroOrMore(...),
                38 => self::reduceRangeFromTo(...),
                41 => self::reduceRangeFrom(...),
                42 => self::reduceRangeTo(...),
                43 => self::reduceRangeExactly(...),
            ],
            startTokens: [
                [
                    3 => true,
                    true,
                    true,
                    true,
                    11 => true,
                    26 => true,
                ],
                [
                    3 => true,
                    true,
                    true,
                    true,
                    11 => true,
                    26 => true,
                ],
                [
                    3 => true,
                ],
                [
                    4 => true,
                ],
                [
                    5 => true,
                ],
                [
                    6 => true,
                ],
                [
                    11 => true,
                    26 => true,
                ],
                [
                    11 => true,
                ],
                [
                    11 => true,
                ],
                [
                    26 => true,
                ],
                [
                    7 => true,
                    true,
                ],
                [
                    7 => true,
                    true,
                ],
                [
                    7 => true,
                ],
                [
                    8 => true,
                ],
                [
                    8 => true,
                ],
                [
                    10 => true,
                ],
                [
                    9 => true,
                    14 => true,
                    16 => true,
                    25 => true,
                    true,
                ],
                [
                    9 => true,
                    14 => true,
                    16 => true,
                    25 => true,
                    true,
                ],
                [
                    9 => true,
                    14 => true,
                    16 => true,
                    25 => true,
                    true,
                ],
                [
                    9 => true,
                    14 => true,
                    16 => true,
                    25 => true,
                    true,
                ],
                [
                    14 => true,
                ],
                [
                    14 => true,
                ],
                [
                    15 => true,
                ],
                [
                    16 => true,
                ],
                [
                    16 => true,
                ],
                [
                    17 => true,
                ],
                [
                    9 => true,
                ],
                [
                    9 => true,
                ],
                [
                    26 => true,
                ],
                [
                    25 => true,
                ],
                [
                    18 => true,
                    true,
                    true,
                    true,
                ],
                [
                    18 => true,
                    true,
                    true,
                    true,
                ],
                [
                    18 => true,
                ],
                [
                    19 => true,
                ],
                [
                    20 => true,
                ],
                [
                    21 => true,
                ],
                [
                    21 => true,
                ],
                [
                    23 => true,
                    true,
                ],
                [
                    24 => true,
                ],
                [
                    24 => true,
                ],
                [
                    23 => true,
                ],
                [
                    24 => true,
                ],
                [
                    23 => true,
                ],
                [
                    24 => true,
                ],
                [
                    22 => true,
                ],
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    13 => true,
                ],
                [
                    12 => true,
                ],
                [
                    12 => true,
                ],
            ],
            matchesEmptyInput: [
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
            ],
            presentInTree: [
                true,
                false,
                true,
                true,
                true,
                true,
                true,
                false,
                true,
                false,
                false,
                false,
                true,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                true,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                true,
                false,
                false,
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
            ],
        );
    }

    private static function reduceTokenDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createTokenDeclaration($ctx, $children);
    }

    private static function reduceSkippedTokenDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createSkippedTokenDeclaration($ctx, $children);
    }

    private static function reducePragmaDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createPragmaDeclaration($ctx, $children);
    }

    private static function reduceIncludeDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createIncludeDeclaration($ctx, $children);
    }

    private static function reduceRuleDeclaration(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRuleDeclaration($ctx, $children);
    }

    private static function reduceKeptMarker(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return true;
    }

    private static function reduceCodeReducer(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createCodeReducer($ctx, $children);
    }

    private static function reduceClassReducer(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createClassReducer($ctx, $children);
    }

    private static function reduceAlternation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createAlternation($ctx, $children);
    }

    private static function reduceConcatenation(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createConcatenation($ctx, $children);
    }

    private static function reduceSuffixed(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRepetition($ctx, $children);
    }

    private static function reduceKeptTokenReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createKeptTokenReference($ctx, $children);
    }

    private static function reduceSkippedTokenReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createSkippedTokenReference($ctx, $children);
    }

    private static function reduceRuleReference(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRuleReference($ctx, $children);
    }

    private static function reduceInlinePattern(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createInlinePattern($ctx, $children);
    }

    private static function reduceZeroOrOne(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createZeroOrOne($ctx, $children);
    }

    private static function reduceOneOrMore(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createOneOrMore($ctx, $children);
    }

    private static function reduceZeroOrMore(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createZeroOrMore($ctx, $children);
    }

    private static function reduceRangeFromTo(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRangeFromTo($ctx, $children);
    }

    private static function reduceRangeFrom(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRangeFrom($ctx, $children);
    }

    private static function reduceRangeTo(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRangeTo($ctx, $children);
    }

    private static function reduceRangeExactly(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \Phplrt\Compiler\Syntax\PP2\PP2NodeFactory::createRangeExactly($ctx, $children);
    }
}
