name: subsplit

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  subsplit:
    name: Split Packages (${{ matrix.package.local_path }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          # Components
          - local_path: 'libs/components/lexer'
            split_repository: 'lexer'
          - local_path: 'libs/components/compiler'
            split_repository: 'compiler'
          - local_path: 'libs/components/exception'
            split_repository: 'exception'
          - local_path: 'libs/components/lexer-builder'
            split_repository: 'lexer-builder'
          - local_path: 'libs/components/parser'
            split_repository: 'parser'
          - local_path: 'libs/components/parser-builder'
            split_repository: 'parser-builder'
          - local_path: 'libs/components/source'
            split_repository: 'source'
          # Contracts
          - local_path: 'libs/contracts/lexer'
            split_repository: 'lexer-contracts'
          - local_path: 'libs/contracts/parser'
            split_repository: 'parser-contracts'
          - local_path: 'libs/contracts/source'
            split_repository: 'source-contracts'
          # Metadata
          - local_path: 'libs/meta/runtime'
            split_repository: 'runtime'
          # Documentation
          - local_path: 'docs'
            split_repository: 'docs'
          # Examples
          - local_path: 'grammars'
            split_repository: 'grammars'
    steps:
      - uses: actions/checkout@v7

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package.split_repository }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: "master"
          package_directory: '${{ matrix.package.local_path }}'
          repository_organization: 'phplrt'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          branch: "master"
          package_directory: '${{ matrix.package.local_path }}'
          repository_organization: 'phplrt'
          repository_name: '${{ matrix.package.split_repository }}'
          user_name: "SerafimArts"
          user_email: "nesk@xakep.ru"
