<?php

/**
 * This file is part of phplrt package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phplrt\Parser;

/**
 * Trait ContextOptionsTrait
 *
 * @mixin ContextOptionsInterface
 */
trait ContextOptionsTrait
{
    /**
     * @var array
     */
    protected array $options = [];

    /**
     * {@inheritDoc}
     */
    public function getOptions(): array
    {
        return $this->options;
    }

    /**
     * {@inheritDoc}
     */
    public function getOption(string $name, $default = null)
    {
        return $this->options[$name] ?? $default;
    }

    /**
     * {@inheritDoc}
     */
    public function hasOption(string $name): bool
    {
        //
        // Options access optimisation:
        //
        // Operator "isset" transforms to
        // "ZEND_ISSET_ISEMPTY_VAR" ZendVM opcode which 2-3 times faster than
        // "DO_FCALL" generated by "array_key_exists" function.
        //
        return isset($this->options[$name]) || \array_key_exists($name, $this->options);
    }
}
